CREATE TABLE pedidos (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id           VARCHAR(255) NOT NULL,
    status               VARCHAR(30)  NOT NULL,
    valor_total          NUMERIC(19, 2) NOT NULL,
    tentativas_pagamento INTEGER      NOT NULL DEFAULT 0,
    criado_em            TIMESTAMP WITH TIME ZONE NOT NULL,
    versao               BIGINT
);

CREATE TABLE itens_pedido (
    pedido_id      BIGINT       NOT NULL REFERENCES pedidos (id) ON DELETE CASCADE,
    produto_id     VARCHAR(255) NOT NULL,
    nome_produto   VARCHAR(255),
    quantidade     INTEGER      NOT NULL,
    preco_unitario NUMERIC(19, 2) NOT NULL
);

CREATE INDEX idx_pedidos_cliente_id ON pedidos (cliente_id);
CREATE INDEX idx_itens_pedido_pedido_id ON itens_pedido (pedido_id);
