CREATE TABLE historico_pedido (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id         BIGINT       NOT NULL,
    tipo_evento       VARCHAR(40)  NOT NULL,
    status_resultante VARCHAR(30)  NOT NULL,
    valor_total       NUMERIC(19, 2),
    correlation_id    VARCHAR(255),
    ocorrido_em       TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_historico_pedido_pedido_id ON historico_pedido (pedido_id);
